version: "3"
services:
  app:
    container_name: handsoutbuild-${NODE_ENV}
    # deploy:
    #   mode: replicated
    #   replicas: 2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:${PORT}"
    restart: always
  # Add other services (e.g., a database service) if necessary
